#pragma once


namespace forward
{
	#define IA_VERTEX_INPUT_RESOURCE_SLOT_COUNT 32

	enum PrimitiveTopologyType
	{
		PT_UNDEFINED ,
		PT_POINTLIST ,
		PT_LINELIST ,
		PT_LINESTRIP ,
		PT_TRIANGLELIST ,
		PT_TRIANGLESTRIP ,
		PT_LINELIST_ADJ ,
		PT_LINESTRIP_ADJ ,
		PT_TRIANGLELIST_ADJ ,
		PT_TRIANGLESTRIP_ADJ ,
		PT_1_CONTROL_POINT_PATCHLIST ,
		PT_2_CONTROL_POINT_PATCHLIST ,
		PT_3_CONTROL_POINT_PATCHLIST ,
		PT_4_CONTROL_POINT_PATCHLIST ,
		PT_5_CONTROL_POINT_PATCHLIST ,
		PT_6_CONTROL_POINT_PATCHLIST ,
		PT_7_CONTROL_POINT_PATCHLIST ,
		PT_8_CONTROL_POINT_PATCHLIST ,
		PT_9_CONTROL_POINT_PATCHLIST ,
		PT_10_CONTROL_POINT_PATCHLIST,
		PT_11_CONTROL_POINT_PATCHLIST,
		PT_12_CONTROL_POINT_PATCHLIST,
		PT_13_CONTROL_POINT_PATCHLIST,
		PT_14_CONTROL_POINT_PATCHLIST,
		PT_15_CONTROL_POINT_PATCHLIST,
		PT_16_CONTROL_POINT_PATCHLIST,
		PT_17_CONTROL_POINT_PATCHLIST,
		PT_18_CONTROL_POINT_PATCHLIST,
		PT_19_CONTROL_POINT_PATCHLIST,
		PT_20_CONTROL_POINT_PATCHLIST,
		PT_21_CONTROL_POINT_PATCHLIST,
		PT_22_CONTROL_POINT_PATCHLIST,
		PT_23_CONTROL_POINT_PATCHLIST,
		PT_24_CONTROL_POINT_PATCHLIST,
		PT_25_CONTROL_POINT_PATCHLIST,
		PT_26_CONTROL_POINT_PATCHLIST,
		PT_27_CONTROL_POINT_PATCHLIST,
		PT_28_CONTROL_POINT_PATCHLIST,
		PT_29_CONTROL_POINT_PATCHLIST,
		PT_30_CONTROL_POINT_PATCHLIST,
		PT_31_CONTROL_POINT_PATCHLIST,
		PT_32_CONTROL_POINT_PATCHLIST
	};
}